# Generated by Django 5.0.4 on 2024-07-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_recipe_recipe_description_recipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='recipedescription',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='recipeimage',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='recipename',
        ),
    ]
