# Generated by Django 5.0.4 on 2024-07-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_recipe_description_recipe_recipedescription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Food',
        ),
    ]
