# Generated by Django 5.0.4 on 2024-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_recipe_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='recipedescription',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='recipeimage',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='recipename',
            new_name='recipe_name',
        ),
    ]
